name: RC Tests

on:
    push:
        branches:
            - rc

jobs:
    e2e-tests:
        runs-on: ubuntu-latest

        container:
            image: mcr.microsoft.com/playwright:v1.37.0-jammy

        env:
            DEBUG: pw:browser*
            NODE_ENV: development

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install dependencies
              run: yarn install

            - name: Run e2e tests
              run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn e2e
